import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'AL-NFLY',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`bg-dark ${inter.className}`}>
      <header>
        <div>
          <nav className='flex justify-between items-center px-48 py-4 border-b border-b-gray-500'>
            <Link
              href='/'
              className='bg-gradient-to-r from-primary to-secondary bg-clip-text text-transparent font-extrabold text-3xl px-2'
              >
            AL
            </Link>
            <ul className='flex justify-between gap-12 font-semibold'>
              <li>
                <a href="/" className='hover:bg-gradient-to-r from-primary to-secondary hover:bg-clip-text hover:text-transparent duration-300'>
                Home 
                </a>
              </li>

              <li>
                <a href="#projects" className='hover:bg-gradient-to-r from-primary to-secondary hover:bg-clip-text hover:text-transparent duration-300'>
                Projects
                </a>
              </li>

              <li>
                <a href="" className='hover:bg-gradient-to-r from-primary to-secondary hover:bg-clip-text hover:text-transparent duration-300'>
                About Me
                </a>
              </li>


              <li>
                <a href="" className='hover:bg-gradient-to-r from-primary to-secondary hover:bg-clip-text hover:text-transparent duration-300'>
                  Contact
                </a>
              </li>
            </ul>
          </nav>
        </div>
      </header>
        {children}
      </body>
    </html>
  )
}
