import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'AL-NFLY',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <body className={`bg-dark text-white  ${inter.className}`}>
    <header>
            <nav className='flex justify-between items-center px-48 max-sm:px-8 py-4'>
              <Link
                href='/'
                className='flex font-extrabold text-3xl px-2 bg-gradient-to-r from-primary to-secondary bg-clip-text text-transparent'
                >
              AL
              </Link>
              <ul className='flex gap-12 max-sm:gap-5 font-semibold max-sm:text-sm'>
                <li>
                  <a href="/" className='hover:bg-gradient-to-r from-primary to-secondary hover:bg-clip-text hover:text-transparent duration-300'>
                  Home 
                  </a>
                </li>

                <li>
                  <a href="#projects" className='hover:bg-gradient-to-r from-primary to-secondary hover:bg-clip-text hover:text-transparent duration-300'>
                  Projects
                  </a>
                </li>

                <li>
                  <a href="" className='hover:bg-gradient-to-r from-primary to-secondary hover:bg-clip-text hover:text-transparent duration-300'>
                  About
                  </a>
                </li>


                <li>
                  <a href="" className='hover:bg-gradient-to-r from-primary to-secondary hover:bg-clip-text hover:text-transparent duration-300'>
                    Contact
                  </a>
                </li>
              </ul>
            </nav>
        </header>
      {children}
    </body>
  </html>
  )
}
